Userdefined form Updates
werkbot/silverstripe-spam-module pull request #3
Opened 2022-07-25 18:01 UTC by SnowB1

- Added timer to be configurable inside silverstripe admin
- Updated error messages to only show 1 time even if both field types are added
- Update to allow for the custom error messages to display

### Summary
> Updated for userdefined form issues https://werkbotstudios.teamwork.com/#/tasks/29058693

### Testing Steps
- [ ] run dev/build
- [ ] Add both field types and test with custom error messages
- [ ] Verify only one message shows
- [ ] Test timer min time set in the admin and that this works as expected

2022-07-25 22:55 UTC, aletail requested changes
Getting this error:
```
[Emergency] Uncaught Error: Class "Werkbot\SpamProtection\Injector" not found
```

2022-07-26 13:54 UTC, SnowB1 commented
> Getting this error:
> 
> ```
> [Emergency] Uncaught Error: Class "Werkbot\SpamProtection\Injector" not found
> ```

Not sure but these were there and must have been removed when I combined a couple things.

2022-07-26 18:40 UTC, aletail requested changes
You are still missing some namespaces, not sure the issue:
- SilverStripe\Control\HTTPRequest
- SilverStripe\Forms\NumericField

Missing on a few of the php classes

Once I added those, it worked great. So just double check all your namespaces

2022-07-27 12:35 UTC, aletail approved these changes
This looks good!

2022-07-29 10:39 UTC, merged